export const SET_ANSWER_ID = 'SET_ANSWER_ID'
export const ADD_NEW_ANSWER_RESPONSE = 'ADD_NEW_ANSWER_RESPONSE';
export const SET_NEED_TO_SEND_ANSWER = 'SET_NEED_TO_SEND_ANSWER';

export const ADD_SUGGESTION_PICK_RESPONSE = 'ADD_SUGGESTION_PICK_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';

export const SET_REGIONS = 'SET_REGIONS'
export const SET_HOSPITALS = 'SET_HOSPITALS'

export const SET_VIDAS = 'SET_VIDAS';
export const SET_PARA_QUEM = 'SET_PARA_QUEM';
export const SET_SHOW_REGIONAL = 'SET_SHOW_REGIONAL';
export const SET_SHOW_NACIONAL = 'SET_SHOW_NACIONAL';
export const SET_PLANO_ANTERIOR = 'SET_PLANO_ANTERIOR';
export const SET_REASON = 'SET_REASON';
export const SET_CNPJ = 'SET_CNPJ';
export const SET_IDADEPF = 'SET_IDADEPF';
export const SET_DELETE_COUNTER_PF = 'SET_DELETE_COUNTER_PF';
export const SET_IDADEPJ = 'SET_IDADEPJ';
export const SET_DELETE_COUNTER_PJ = 'SET_DELETE_COUNTER_PJ';
export const SET_SHOW_ENFERMARIA = 'SET_SHOW_ENFERMARIA';
export const SET_SHOW_APARTAMENTO = 'SET_SHOW_APARTAMENTO';
export const SET_OCUPACAO = 'SET_OCUPACAO';
export const SET_OCCUPATION_NOT_FOUND = 'SET_OCCUPATION_NOT_FOUND';
export const SET_HOSPITAL = 'SET_HOSPITAL';
export const SET_HOSPITAL_TYPE = 'SET_HOSPITAL_TYPE';
export const SET_QUEMSERAINCLUIDO = 'SET_QUEMSERAINCLUIDO';
export const SET_NAME = 'SET_NAME';
export const SET_TELEPHONE_DDI = 'SET_TELEPHONE_DDI';
export const SET_TELEPHONE_DDD = 'SET_TELEPHONE_DDD';
export const SET_EMAIL = 'SET_EMAIL';

export const SIGN_IN_RESPONSE = 'SIGN_IN_RESPONSE'
export const SIGN_IN_PASSWORD_RESPONSE = 'SIGN_IN_PASSWORD_RESPONSE'
export const SEND_CHALLENGE_RESPONSE = 'SEND_CHALLENGE_RESPONSE'
export const CHECK_FOR_SIGNED_USER_RESPONSE = 'CHECK_FOR_SIGNED_USER_RESPONSE'
export const CHECK_PHONE_RESPONSE = 'CHECK_PHONE_RESPONSE'
export const SIGN_UP_ADD_INFO_RESPONSE = 'SIGN_UP_ADD_INFO_RESPONSE'
export const SET_CHALLENGE_ANSWER = 'SET_CHALLENGE_ANSWER'
export const SET_COGNITO_PRE_AUTH_USER = 'SET_COGNITO_PRE_AUTH_USER'
export const SET_CHALLENGE_TYPE = 'SET_CHALLENGE_TYPE'
export const SIGN_IN_COGNITO_RESPONSE = 'SIGN_IN_COGNITO_RESPONSE'
export const SIGN_UP_COGNITO_RESPONSE = 'SIGN_UP_COGNITO_RESPONSE'
export const SIGN_IN_ACCOUNT_KIT_RESPONSE = 'SIGN_IN_ACCOUNT_KIT_RESPONSE'
export const GET_ACCOUNT_KIT_RESPONSE = 'GET_ACCOUNT_KIT_RESPONSE'
export const SET_LOGIN_STATE = 'SET_LOGIN_STATE'
export const SET_CODE = 'SET_CODE'
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
export const SET_USER_IS_LOGGED = 'SET_USER_IS_LOGGED'
export const SET_USER_ID_COGNITO = 'SET_USER_ID_COGNITO'
export const SEND_OWN_SMS_RESPONSE = 'SEND_OWN_SMS_RESPONSE'
export const SEND_SNS_SMS_RESPONSE = 'SEND_SNS_SMS_RESPONSE'
export const SET_SEND_CODE_ERROR = 'SET_SEND_CODE_ERROR'
export const CREATE_CODE_RESPONSE = 'CREATE_CODE_RESPONSE'
export const SET_RETURN_TO_URL = 'SET_RETURN_TO_URL'

export const SET_CHALLENGE_CODE_ERROR = 'SET_CHALLENGE_CODE_ERROR'
export const SET_CHALLENGE_LOADING = 'SET_CHALLENGE_LOADING'

export const SET_CITY = 'SET_CITY'
export const SET_LOCATION_STATE = 'SET_LOCATION_STATE'
export const SET_OCCUPATION_LIST = 'SET_OCCUPATION_LIST'
export const SET_HOSPITAL_LIST = 'SET_HOSPITAL_LIST'
export const SET_REGION_LIST = 'SET_REGION_LIST'
export const SET_IS_CAPITAL = 'SET_IS_CAPITAL'
export const GEO_LOCATION_BROWSER_RESPONSE = 'GEO_LOCATION_BROWSER_RESPONSE'
export const GEO_LOCATION_IP_RESPONSE = 'GEO_LOCATION_IP_RESPONSE'
export const REGION_HOSPITAL_OCCUPATION_BY_STATE_RESPONSE = 'REGION_HOSPITAL_OCCUPATION_BY_STATE_RESPONSE'

export const GET_SUGGESTIONS_RESPONSE = 'GET_SUGGESTIONS_RESPONSE'
export const SET_SUGGESTIONS = 'SET_SUGGESTIONS'
export const SET_AGES_ARRAY = 'SET_AGES_ARRAY'
export const SET_SHOW_HOSPITALAR = 'SET_SHOW_HOSPITALAR'
export const SET_SHOW_AMBULATORIAL = 'SET_SHOW_AMBULATORIAL'
export const SET_SHOW_COPARTICIPACAO = 'SET_SHOW_COPARTICIPACAO'
export const SET_SHOW_WITHOUT_HOSPITAL = 'SET_SHOW_WITHOUT_HOSPITAL'
export const SET_SHOW_OUTSIDE_REGION = 'SET_SHOW_OUTSIDE_REGION'
export const SET_SUGGESTION_SHOW_REGIONAL = 'SET_SUGGESTION_SHOW_REGIONAL'
export const SET_SUGGESTION_SHOW_NACIONAL = 'SET_SUGGESTION_SHOW_NACIONAL'
export const SET_SUGGESTION_SHOW_ENFERMARIA = 'SET_SUGGESTION_SHOW_ENFERMARIA'
export const SET_SUGGESTION_SHOW_APARTAMENTO = 'SET_SUGGESTION_SHOW_APARTAMENTO'

export const SET_PLANO_ID = 'SET_PLANO_ID'
export const SET_PLAN_DETAILS = 'SET_PLAN_DETAILS'
export const GET_SUGGESTION_DETAILS_RESPONSE = 'GET_SUGGESTION_DETAILS_RESPONSE'

export const ADD_HUGGY_WIDGET_RESPONSE = 'ADD_HUGGY_WIDGET_RESPONSE'

export const VIEW_PAGE = 'VIEW_PAGE'

export const FORM_NEXT_PAGE = 'FORM_NEXT_PAGE'
export const FORM_END = 'FORM_END'
export const SUGGESTION_PICK_BUTTON_ACTION = 'SUGGESTION_PICK_BUTTON_ACTION'
export const SET_AB_PREFERENCE = 'SET_AB_PREFERENCE'
